### ISSUE TITLE
Welcome system does not work

### ISSUE THREAD

**Issue by alex12266** [IGRohan/IGBot#10]
I made the entry to my server where the bot is and it does not generate the welcome image or the greeting although no error is registered in the console of the server where the bot is hosted
![image](https://user-images.githubusercontent.com/74673312/119205969-77d46600-ba5f-11eb-9890-97ee65938640.png)

**Comment by IGRohan** [comment]
an issue with the package, not sure when it'll be fixed, but its not my issue so i can't help
