### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by unknowndiscorduser** [IGRohan/IGBot#7]
Is your bot commands all clone of 
https://github.com/Androz2091/AtlantaBot
??
cause all the commands seems to be same 
Just asking.
Peace | ✌️ 

love from
-India
hehe

**Comment by IGRohan** [comment]
some of them yes, i started making bots after using Atlanta, you can say the README file is kind of like his.
But there are a lot of differences, take a look and you'll see 👍
